server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/keg?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
logging:
  level:
    com.ysu: debug
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
ysu:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5  # 密钥
    expire: 604800  # token有效时长，7天，单位秒
    header: Authorization
